services:
  web:
    container_name: dinamiques-web-next
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - .env
    restart: unless-stopped
    network_mode: bridge

volumes:
  node_modules:
