services:
  web-dev:
    container_name: dinamiques-web-next-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    network_mode: bridge

  web-prod:
    container_name: dinamiques-web-next
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '4000:4000'
    env_file:
      - .env
    restart: unless-stopped
    network_mode: bridge

volumes:
  node_modules:
